#!/bin/bash
alias cs401='cd ~/school/cs401R/NLP/'
alias cs450='cd ~/school/cs450'
alias cs478='cd ~/school/cs478'
alias cs601='cd ~/school/cs601R'
alias pso='cd ~/python/amlpso'
alias papers='cd ~/papers'
