
# Load compatible rc file (for aliases and variables)
. $HOME/.shrc

# Vi mode:
set -o vi

# Set the prompt
PS1="\u:\W$ "

# Ignore repeat commands in .bash_history
export HISTCONTROL=ignoredups
# Append to history instead of overwriting it
shopt -s histappend
# Whenever the prompt is displayed, write the previous command to disk
export PROMPT_COMMAND='history -a'

# Enable programmable completion
source /etc/bash_completion
