
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Load compatible rc file (for aliases and variables)
. $HOME/.shrc

# Vi mode:
set -o vi

# Whenever the prompt is displayed, write the previous command to disk
#export PROMPT_COMMAND='history -a' # we put this into the following line

# Set up some variables that we'll use when making the prompt
export PROMPT_COMMAND='history -a;
export MEM_TOTAL=$(( `sed -n "s/MemTotal:[\t ]\+\([0-9]\+\) kB/\1/p" /proc/meminfo`
/ 1024))MB;
export MEM_USED=$(( `free |grep "buffers/cache" \
|sed "s/.*buffers\/cache:[\t ]\+\([0-9]\+\).*/\1/"` / 1024));
export CPU_USED=`cat /proc/loadavg |cut -d" " -f1`;
export PS1="\n\u@\h:\w\nRAM: $MEM_USED/$MEM_TOTAL  CPU: $CPU_USED\n$ ";
'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Ignore repeat commands in .bash_history
export HISTCONTROL=ignoredups

# Append to history instead of overwriting it
shopt -s histappend

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Some rather silly people decided to put miserable functionality as default
# in Fedora 13 and beyond.  This disables it.
unset -f command_not_found_handle

# Enable programmable completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix
then
    source /etc/bash_completion
fi
