#!/bin/bash

##############################################################################
# Path

pathdirs=(
		# On my laptop
		/opt/local/bin
		/opt/local/sbin
		/Library/Frameworks/Python.framework/Versions/Current/bin

		# On the lab machines
		$HOME/admin/bin
		$HOME/bin
		)

for dir in ${pathdirs[@]}
do
	if [[ -d $dir ]]
	then
		if [[ $PATH == "" ]]
		then
			export PATH="$dir"
		else
			export PATH="$PATH:$dir"
		fi
	fi
done

# I like not having to type ./ before running an executable.  Maybe that's 
# sacrilegious, but oh well.
export PATH=$PATH::

##############################################################################
# Python Path

pythondirs=(
			$HOME/python 
			$HOME/python/amlpso 
			$HOME/python/evilplot 
			$HOME/python/util
			/Library/Python/2.5/site-packages
			$HOME/clone/smug
			$HOME/clone
			)

export PYTHONPATH=""

for dir in ${pythondirs[@]}
do
	if [[ -d $dir ]]
	then
		if [[ $PYTHONPATH == "" ]]
		then
			export PYTHONPATH="$dir"
		else
			export PYTHONPATH="$PYTHONPATH:$dir"
		fi
	fi
done

set -o vi


# Aliases that are machine specific
if [[ -e $HOME/.aliases ]]
then 
	. $HOME/.aliases
fi

# Aliases that I want on all of my machines
alias convertalltoeps='for file in `ls *.pgm`; do convert $file `basename $file .pgm`.eps; done; for file in `ls *.ppm`; do convert $file `basename $file .ppm`.eps; done'
alias rm='rm -i'
alias pushall="git commit -a -m'.'; git push;"
alias pretty1="enscript -GE"
alias pretty2="enscript -G2rE"

# Some system specific stuff
if [[ `hostname` == "matthew-gardners-computer.local" ]]
then
	export MYSQL_HOME=~/Documents/mysql-5.0.51b-osx10.5-x86
	export LIBRARY_PATH=/opt/local/lib
	export CPLUS_INCLUDE_PATH=/opt/local/include
	export PKG_CONFIG_PATH=/opt/local/include/gtkmm-2.4:/opt/local/include/gtkmm-2.0:/opt/local/lib/pkgconfig:/usr/X11R6/lib/pkgconfig
	export DYLD_FALLBACK_LIBRARY_PATH=/opt/local/lib:/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A
	export CLICOLOR=1
	export LSCOLORS=gxfxcxdxcxegedabaggxgx
	export EDITOR=vim
	alias ls='ls -G'
else
	# This is because I use a black terminal on my mac, but a white terminal
	# in linux.  I want different colors on the different systems.  So it turns
	# out that $TERM is xterm-color on the mac, and just xterm in linux, so
	# this works.
	alias ls='ls --color=always'
	if [[ $TERM == "xterm-color" ]]
	then
		export LS_COLORS="di=36:ln=35:so=32:pi=33:ex=32:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:*.py=33"
	else
		export LS_COLORS=""
	fi
fi
