#!/bin/bash

export PATH=:$PATH:$HOME/admin/bin:$HOME/bin

pythondirs=(
			$HOME/python 
			$HOME/python/amlpso 
			$HOME/python/evilplot 
			$HOME/google-opt
			$HOME/clone/pssh
			)

##############################################################################
# Python Path

export PYTHONPATH=""

for dir in ${pythondirs[@]}
do
	if [[ -d $dir ]]
	then
		if [[ $PYTHONPATH == "" ]]
		then
			export PYTHONPATH="$dir"
		else
			export PYTHONPATH="$PYTHONPATH:$dir"
		fi
	fi
done

set -o vi

# This is because I use a black terminal on my mac, but a white terminal
# in the lab.  I want the colors to change if I'm logged in from the mac,
# but to use the default colors in the lab.  So it turns out that $TERM
# is xterm-color on the mac, and just xterm in the lab, so this works.
if [[ $TERM == "xterm-color" ]]
then
	export LS_COLORS="di=36:ln=35:so=32:pi=33:ex=32:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:*.py=33"
else
	export LS_COLORS=""
fi

# Aliases that I want on all of my machines
alias convertalltoeps='for file in `ls *.pgm`; do convert $file `basename $file .pgm`.eps; done; for file in `ls *.ppm`; do convert $file `basename $file .ppm`.eps; done'
alias ls='ls --color=always'
alias rm='rm -i'
alias pushall="git commit -a -m'.'; git push;"

PS1="\u:\W$ "


