" Use Vim settings, rather then Vi settings (usually better).
" This must be first, because it changes other options as a side effect.
set nocompatible

syntax on
if has("autocmd")
	" When editing a file, always jump to the last curser position
	autocmd BufReadPost *
	\ if line("'\"") > 0 && line ("'\"") <= line("$") |
	\   exe "normal! g'\""  |
	\ endif

	" Allow filetype detection, plugins, and indenting
	filetype plugin indent on
	" For python you want 4 spaces to be a tab, and tabs should be expanded
	autocmd FileType python setlocal et sw=4 sts=4
	autocmd FileType python set foldlevel=1
	" Use the skeletons when opening python and latex files
	autocmd BufNewFile *.py r ~/.vim/skel.py
	autocmd BufNewFile *.tex r ~/.vim/skel.tex
	" Gets rid of an extra line that gets put in
    autocmd BufNewFile *.py exe "normal 1Gddj"
    autocmd BufNewFile *.tex exe "normal 1Gddj"
	" Use django file type for html files, 'cause I don't do any other html
    autocmd BufEnter *.html setfiletype htmldjango

endif
" Get rid of the annoying default plaintex for empty .tex files
let g:tex_flavor='latex'

" Make a mapping to do spellchecking
nmap <silent> <F3> :setlocal spell spelllang=en_us<cr>

" Allow lower case to match upper case search targets.
set smartcase

" Always show the status line
set laststatus=2

" ReST editing stuff
function ReST_Extend_Line()
    let cur = getline(".")
    let prev = getline( line(".") - 1 )
    return repeat(cur[0], len(prev) - len(cur))
endfunction
imap <F9> <c-r>=ReST_Extend_Line()<cr>
map <F9> yypVr

" Don't use Ex mode.
map Q <nop>

" Tab completion for ex command-line (like :split)
set wildmenu
set wildmode=longest:full,full

" When at the top or bottom of the terminal, always leave 2 lines above the
" curser
set scrolloff=2

" Some folding options
set foldenable
set foldlevelstart=0
set foldopen=block,insert,hor,jump,mark,percent,quickfix,search,tag,undo
" Maps F2 to getting rid of the highlighting after a search - very nice
nmap <silent> <F2> :nohl<cr>:set spelllang=<cr>
" Resize windows with + and _, instead of the C-W stuff
nmap + <C-W>+
nmap _ <C-W>-
" Tabs should be four spaces long, not eight
set sw=4
set ts=4
set hlsearch " Highlight the last used search pattern
set ruler " show the cursor position all the time

