#!/bin/bash

killall -9 papermon.sh
$HOME/bin/papermon.sh &

##############################################################################
# Keyboard layout stuff

# For some reason this doesn't actually work with xfce4 (and maybe gnome).  I
# think it's because it has to run after the xfce4-xkb-plugin loads, which is
# later.  But I don't know where to put it.  So at least I have these commands
# here and can run them manually once on a system install, then have everything
# work until I reinstall.

# Switch keyboard layouts when left win is pressed, and toggle with menu key
setxkbmap -layout 'us,si,gr,es'
setxkbmap -variant ',us,polytonic,deadtilde'

# Switch keyboard layouts when left win is pressed, and toggle with menu key
setxkbmap -option grp:lwin_switch
setxkbmap -option grp:menu_toggle
setxkbmap -option grp:rwin_toggle # on a Mac laptop running linux, because the
# command keys are considered lwin and rwin

# Enable horizontal scrolling
synclient HorizTwoFingerScroll=1

##############################################################################
# Start Session

if [[ -x /usr/bin/startxfce4 ]]; then
    # XFCE4

    . $HOME/.xsession-xfconf

    /usr/bin/startxfce4
else
    # GNOME

    # Load gconf settings
    ($HOME/.xsession-gconf) &

    disable_autostart()
    {
        SYSDIR="/etc/xdg/autostart"
        LOCALDIR="$HOME/.config/autostart"
        mkdir -p "$LOCALDIR"
        cp "$SYSDIR/$1.desktop" "$LOCALDIR"
        echo "X-GNOME-Autostart-enabled=false" >>"$LOCALDIR/$1.desktop"
    }

    # By the way, there's no need to disable services if the desktop file has an
    # AutostartCondition line.

    # Bluetooth (re-enable if and when I ever need it):
    disable_autostart bluetooth-applet
    # Silly backup tool:
    disable_autostart deja-dup-monitor
    # GNOME personal file sharing:
    disable_autostart gnome-user-share
    # PackageKit Applet:
    disable_autostart gpk-update-icon
    # SELinux restorecond:
    disable_autostart restorecond
    # SELinux troubleshooter:
    disable_autostart sealertauto
    # Silly home directory mangler:
    disable_autostart user-dirs-update-gtk
    # XScreenSaver (I use GNOME ScreenSaver):
    disable_autostart xscreensaver-autostart

    ##########################################################################
    # Window/Session Manager

    # which window manager (metacity or compiz)
    gconftool-2 --type string --set /apps/gnome-session/rh/window_manager metacity

    gnome-session
fi

# Get rid of any straggler children
kill %1 %2 %3 %4 %5 %6 %7 %8
